version: '3'

services:
  cassandra1:
    container_name: cassandra1
    image: cassandra:latest
    volumes:
      - cassandra1-data:/var/lib/cassandra/data
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=Cascluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=cascenter
    restart: always
    logging: 
      driver: none

  cassandra2:
    container_name: cassandra2
    image: cassandra:latest
    volumes:
      - cassandra2-data:/var/lib/cassandra/data
    ports:
      - 9043:9042
    command: bash -c 'sleep 60; /docker-entrypoint.sh cassandra -f'
    depends_on: 
      - cassandra1
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=Cascluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=cascenter
      - CASSANDRA_SEEDS=cassandra1
    restart: always
    logging: 
      driver: none

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    depends_on: 
      - cassandra1
    volumes: 
      - ./script.cql:/setup.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra1 -f /setup.cql"

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --requirepass fh7gdGDds34
    ports: 
      - "6379:6379"
    volumes: 
      - redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment: 
      - REDIS_REPLICATION_MODE=master
    restart: always
    logging: 
      driver: none

  wppdiscovery:
    container_name: wppdiscovery
    build: ./src
    environment: 
      cassandra_host: cassandra2
      redis_host: redis
    command: /bin/sh -c "sleep 20 && /wppdiscovery"
    depends_on: 
      - cassandra-load-keyspace
      - redis

volumes:
  cassandra1-data:
  cassandra2-data:
  redis-data:
