version: '3'

services:
  cassandra1:
    container_name: cassandra1
    image: cassandra:latest
    volumes:
      - cassandra1-data:/var/lib/cassandra/data
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=Cascluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=cascenter
    restart: always

  cassandra2:
    container_name: cassandra2
    image: cassandra:latest
    volumes:
      - cassandra2-data:/var/lib/cassandra/data
    ports:
      - 9043:9042
    command: bash -c 'sleep 60; /docker-entrypoint.sh cassandra -f'
    depends_on: 
      - cassandra1
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=Cascluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=cascenter
      - CASSANDRA_SEEDS=cassandra1
    restart: always

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    depends_on: 
      - cassandra2
    volumes: 
      - $PWD/script.cql:/setup.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra2 -f /setup.cql"

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --requirepass fh7gdGDds34
    ports: 
      - "6379:6379"
    volumes: 
      - redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment: 
      - REDIS_REPLICATION_MODE=master
    networks: 
      redis_net:
        ipv4_address: 172.28.1.4
    restart: always

volumes:
  cassandra1-data:
  cassandra2-data:
  redis-data:

networks: 
  redis_net:
    ipam: 
      driver: default
      config: 
        - subnet: 172.28.0.0/16